import groovy.json.JsonSlurper

plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

def packageVersion = new JsonSlurper().parse(file('../package.json')).version

group = 'expo.modules.googletagmanager'
version = packageVersion

android {
  namespace "expo.modules.googletagmanager"
  defaultConfig {
    versionCode 1
    versionName packageVersion
  }
}

dependencies {
  api "com.google.android.gms:play-services-tagmanager:18.3.0"
}
